---
platform: linux

image_resource:
  type: mock
  source:
    mirror_self: true
    force_version: ((resource_version))

inputs:
- name: some-resource

params:
  EXPECTED_RESOURCE_SECRET:
  EXPECTED_RESOURCE_VERSION_SECRET:

run:
  path: sh
  args:
  - -ec
  - |
    # test image_resource secret
    test "$MIRRORED_VERSION" = "$EXPECTED_RESOURCE_VERSION_SECRET"

    # test input secret from job (secret is scoped to job's pipeline with execute -j)
    test "$(cat some-resource/resource_secret)" = "$EXPECTED_RESOURCE_SECRET"

    echo all credentials matched expected values
