---
platform: linux

image_resource:
  type: mock
  source:
    mirror_self: true
    force_version: ((resource_version))

params:
  TEAM_SECRET: ((team_secret))
  EXPECTED_TEAM_SECRET:
  EXPECTED_RESOURCE_VERSION_SECRET:

run:
  path: sh
  args:
  - -ec
  - |
    # test image_resource secret
    test "$MIRRORED_VERSION" = "$EXPECTED_RESOURCE_VERSION_SECRET"

    # test team-scoped secret via params
    test "$TEAM_SECRET" = "$EXPECTED_TEAM_SECRET"

    echo all credentials matched expected values
