---
resources:
- name: mockery
  type: mock

jobs:
- name: say-hello
  plan:
  - get: mockery
  - task: hello
    config:
      platform: linux

      image_resource:
        type: mock
        source: {mirror_self: true}

      run:
        path: echo
        args: ["Hello, world!"]
  - put: mockery
    params: {version: put-version}
